# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:11.1.0
  #armhf: ghcr.io/hassio-addons/base/armhf:11.1.0
  #armv7: ghcr.io/hassio-addons/base/armv7:11.1.0
  amd64: ghcr.io/hassio-addons/base/amd64:11.1.0
  i386: ghcr.io/hassio-addons/base/i386:11.1.0
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: pgweb"
  org.opencontainers.image.description: "pgweb"
  org.opencontainers.image.source: "https://github.com/bjeanes/hassio-addons/tree/pgweb"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  PGWEB_VERSION:  0.11.11
